default: &default
  adapter: postgresql
  host: localhost
  username: gnilrets

development:
  <<: *default
  database: amylase-dev

test:
  <<: *default
  database: amylase-test

production:
  <<: *default
  database: amylase-prod
