require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DataSourceGroupsController, :type => :controller do

  def construct_associated_attributes(model, association_ids)
    attributes = model.attributes.with_indifferent_access
    attributes[association_ids] = model.send(association_ids)
    attributes
  end

  # This should return the minimal set of attributes required to create a valid
  # DataSourceGroup. As you add validations to DataSourceGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    valid_build = FactoryGirl.build(:data_source_group, :with_existing_sources)
    construct_associated_attributes(valid_build, :data_source_ids)
  }

  let(:invalid_attributes) {
    # An invalid record is one where the same name already exists
    FactoryGirl.create(:data_source_group).attributes
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DataSourceGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all data_source_groups as @data_source_groups" do
      data_source_group = DataSourceGroup.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:data_source_groups)).to eq([data_source_group])
    end
  end

  describe "GET show" do
    it "assigns the requested data_source_group as @data_source_group" do
      data_source_group = DataSourceGroup.create! valid_attributes
      get :show, {:id => data_source_group.to_param}, valid_session
      expect(assigns(:data_source_group)).to eq(data_source_group)
    end
  end

  describe "GET new" do
    it "assigns a new data_source_group as @data_source_group" do
      get :new, {}, valid_session
      expect(assigns(:data_source_group)).to be_a_new(DataSourceGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested data_source_group as @data_source_group" do
      data_source_group = DataSourceGroup.create! valid_attributes
      get :edit, {:id => data_source_group.to_param}, valid_session
      expect(assigns(:data_source_group)).to eq(data_source_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DataSourceGroup" do
        expect {
          post :create, {:data_source_group => valid_attributes}, valid_session
        }.to change(DataSourceGroup, :count).by(1)
      end

      it "assigns a newly created data_source_group as @data_source_group" do
        post :create, {:data_source_group => valid_attributes}, valid_session
        expect(assigns(:data_source_group)).to be_a(DataSourceGroup)
        expect(assigns(:data_source_group)).to be_persisted
      end

      it "redirects to the created data_source_group" do
        post :create, {:data_source_group => valid_attributes}, valid_session
        expect(response).to redirect_to(DataSourceGroup.last)
      end

      it "creates the DataSourceGroupAssociation records" do
        post :create, {:data_source_group => valid_attributes}, valid_session
        data_source_group = assigns(:data_source_group).reload
        expect(data_source_group.data_sources.count).to be > 0
        expect(data_source_group.data_sources.count).to eq valid_attributes[:data_source_ids].count
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved data_source_group as @data_source_group" do
        post :create, {:data_source_group => invalid_attributes}, valid_session
        expect(assigns(:data_source_group)).to be_a_new(DataSourceGroup)
      end

      it "re-renders the 'new' template" do
        post :create, {:data_source_group => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      before do
        @data_source_group = DataSourceGroup.create! valid_attributes

        # Remove a data source from the group
        @updated_attributes = construct_associated_attributes(@data_source_group, :data_source_ids)
        @updated_attributes[:data_source_ids].pop
      end

      it "updates the requested data_source_group" do
        expect {
          put :update, {:id => @data_source_group.to_param, :data_source_group => @updated_attributes}, valid_session
        }.to change { @data_source_group.data_sources.count }.by(-1)
      end

      it "assigns the requested data_source_group as @data_source_group" do
        put :update, {:id => @data_source_group.to_param, :data_source_group => @updated_attributes}, valid_session
        expect(assigns(:data_source_group)).to eq(@data_source_group)
      end

      it "redirects to the data_source_group" do
        put :update, {:id => @data_source_group.to_param, :data_source_group => @updated_attributes}, valid_session
        expect(response).to redirect_to(@data_source_group)
      end
    end

    describe "with invalid params" do
      it "assigns the data_source_group as @data_source_group" do
        data_source_group = DataSourceGroup.create! valid_attributes
        put :update, {:id => data_source_group.to_param, :data_source_group => invalid_attributes}, valid_session
        expect(assigns(:data_source_group)).to eq(data_source_group)
      end

      it "re-renders the 'edit' template" do
        data_source_group = DataSourceGroup.create! valid_attributes
        put :update, {:id => data_source_group.to_param, :data_source_group => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested data_source_group" do
      data_source_group = DataSourceGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => data_source_group.to_param}, valid_session
      }.to change(DataSourceGroup, :count).by(-1)
    end

    it "redirects to the data_source_groups list" do
      data_source_group = DataSourceGroup.create! valid_attributes
      delete :destroy, {:id => data_source_group.to_param}, valid_session
      expect(response).to redirect_to(data_source_groups_url)
    end
  end

end
