require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExternalCredentialsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ExternalCredential. As you add validations to ExternalCredential, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExternalCredentialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all external_credentials as @external_credentials" do
      external_credential = ExternalCredential.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:external_credentials)).to eq([external_credential])
    end
  end

  describe "GET show" do
    it "assigns the requested external_credential as @external_credential" do
      external_credential = ExternalCredential.create! valid_attributes
      get :show, {:id => external_credential.to_param}, valid_session
      expect(assigns(:external_credential)).to eq(external_credential)
    end
  end

  describe "GET new" do
    it "assigns a new external_credential as @external_credential" do
      get :new, {}, valid_session
      expect(assigns(:external_credential)).to be_a_new(ExternalCredential)
    end
  end

  describe "GET edit" do
    it "assigns the requested external_credential as @external_credential" do
      external_credential = ExternalCredential.create! valid_attributes
      get :edit, {:id => external_credential.to_param}, valid_session
      expect(assigns(:external_credential)).to eq(external_credential)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExternalCredential" do
        expect {
          post :create, {:external_credential => valid_attributes}, valid_session
        }.to change(ExternalCredential, :count).by(1)
      end

      it "assigns a newly created external_credential as @external_credential" do
        post :create, {:external_credential => valid_attributes}, valid_session
        expect(assigns(:external_credential)).to be_a(ExternalCredential)
        expect(assigns(:external_credential)).to be_persisted
      end

      it "redirects to the created external_credential" do
        post :create, {:external_credential => valid_attributes}, valid_session
        expect(response).to redirect_to(ExternalCredential.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved external_credential as @external_credential" do
        post :create, {:external_credential => invalid_attributes}, valid_session
        expect(assigns(:external_credential)).to be_a_new(ExternalCredential)
      end

      it "re-renders the 'new' template" do
        post :create, {:external_credential => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested external_credential" do
        external_credential = ExternalCredential.create! valid_attributes
        put :update, {:id => external_credential.to_param, :external_credential => new_attributes}, valid_session
        external_credential.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested external_credential as @external_credential" do
        external_credential = ExternalCredential.create! valid_attributes
        put :update, {:id => external_credential.to_param, :external_credential => valid_attributes}, valid_session
        expect(assigns(:external_credential)).to eq(external_credential)
      end

      it "redirects to the external_credential" do
        external_credential = ExternalCredential.create! valid_attributes
        put :update, {:id => external_credential.to_param, :external_credential => valid_attributes}, valid_session
        expect(response).to redirect_to(external_credential)
      end
    end

    describe "with invalid params" do
      it "assigns the external_credential as @external_credential" do
        external_credential = ExternalCredential.create! valid_attributes
        put :update, {:id => external_credential.to_param, :external_credential => invalid_attributes}, valid_session
        expect(assigns(:external_credential)).to eq(external_credential)
      end

      it "re-renders the 'edit' template" do
        external_credential = ExternalCredential.create! valid_attributes
        put :update, {:id => external_credential.to_param, :external_credential => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested external_credential" do
      external_credential = ExternalCredential.create! valid_attributes
      expect {
        delete :destroy, {:id => external_credential.to_param}, valid_session
      }.to change(ExternalCredential, :count).by(-1)
    end

    it "redirects to the external_credentials list" do
      external_credential = ExternalCredential.create! valid_attributes
      delete :destroy, {:id => external_credential.to_param}, valid_session
      expect(response).to redirect_to(external_credentials_url)
    end
  end

end
