require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JobSchedulesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # JobSchedule. As you add validations to JobSchedule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JobSchedulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all job_schedules as @job_schedules" do
      job_schedule = JobSchedule.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:job_schedules)).to eq([job_schedule])
    end
  end

  describe "GET show" do
    it "assigns the requested job_schedule as @job_schedule" do
      job_schedule = JobSchedule.create! valid_attributes
      get :show, {:id => job_schedule.to_param}, valid_session
      expect(assigns(:job_schedule)).to eq(job_schedule)
    end
  end

  describe "GET new" do
    it "assigns a new job_schedule as @job_schedule" do
      get :new, {}, valid_session
      expect(assigns(:job_schedule)).to be_a_new(JobSchedule)
    end
  end

  describe "GET edit" do
    it "assigns the requested job_schedule as @job_schedule" do
      job_schedule = JobSchedule.create! valid_attributes
      get :edit, {:id => job_schedule.to_param}, valid_session
      expect(assigns(:job_schedule)).to eq(job_schedule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JobSchedule" do
        expect {
          post :create, {:job_schedule => valid_attributes}, valid_session
        }.to change(JobSchedule, :count).by(1)
      end

      it "assigns a newly created job_schedule as @job_schedule" do
        post :create, {:job_schedule => valid_attributes}, valid_session
        expect(assigns(:job_schedule)).to be_a(JobSchedule)
        expect(assigns(:job_schedule)).to be_persisted
      end

      it "redirects to the created job_schedule" do
        post :create, {:job_schedule => valid_attributes}, valid_session
        expect(response).to redirect_to(JobSchedule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved job_schedule as @job_schedule" do
        post :create, {:job_schedule => invalid_attributes}, valid_session
        expect(assigns(:job_schedule)).to be_a_new(JobSchedule)
      end

      it "re-renders the 'new' template" do
        post :create, {:job_schedule => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested job_schedule" do
        job_schedule = JobSchedule.create! valid_attributes
        put :update, {:id => job_schedule.to_param, :job_schedule => new_attributes}, valid_session
        job_schedule.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested job_schedule as @job_schedule" do
        job_schedule = JobSchedule.create! valid_attributes
        put :update, {:id => job_schedule.to_param, :job_schedule => valid_attributes}, valid_session
        expect(assigns(:job_schedule)).to eq(job_schedule)
      end

      it "redirects to the job_schedule" do
        job_schedule = JobSchedule.create! valid_attributes
        put :update, {:id => job_schedule.to_param, :job_schedule => valid_attributes}, valid_session
        expect(response).to redirect_to(job_schedule)
      end
    end

    describe "with invalid params" do
      it "assigns the job_schedule as @job_schedule" do
        job_schedule = JobSchedule.create! valid_attributes
        put :update, {:id => job_schedule.to_param, :job_schedule => invalid_attributes}, valid_session
        expect(assigns(:job_schedule)).to eq(job_schedule)
      end

      it "re-renders the 'edit' template" do
        job_schedule = JobSchedule.create! valid_attributes
        put :update, {:id => job_schedule.to_param, :job_schedule => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested job_schedule" do
      job_schedule = JobSchedule.create! valid_attributes
      expect {
        delete :destroy, {:id => job_schedule.to_param}, valid_session
      }.to change(JobSchedule, :count).by(-1)
    end

    it "redirects to the job_schedules list" do
      job_schedule = JobSchedule.create! valid_attributes
      delete :destroy, {:id => job_schedule.to_param}, valid_session
      expect(response).to redirect_to(job_schedules_url)
    end
  end

end
