require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TplDevTestsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TplDevTest. As you add validations to TplDevTest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.build(:tpl_dev_test).attributes
  }

  let(:invalid_attributes) {
    FactoryGirl.build(:tpl_dev_test, argument: nil).attributes
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TplDevTestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tpl_dev_tests as @tpl_dev_tests" do
      tpl_dev_test = TplDevTest.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tpl_dev_tests)).to eq([tpl_dev_test])
    end
  end

  describe "GET show" do
    it "assigns the requested tpl_dev_test as @tpl_dev_test" do
      tpl_dev_test = TplDevTest.create! valid_attributes
      get :show, {:id => tpl_dev_test.to_param}, valid_session
      expect(assigns(:tpl_dev_test)).to eq(tpl_dev_test)
    end
  end

  describe "GET new", skip: "No NEW route" do
    it "assigns a new tpl_dev_test as @tpl_dev_test" do
      get :new, {}, valid_session
      expect(assigns(:tpl_dev_test)).to be_a_new(TplDevTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested tpl_dev_test as @tpl_dev_test" do
      tpl_dev_test = TplDevTest.create! valid_attributes
      get :edit, {:id => tpl_dev_test.to_param}, valid_session
      expect(assigns(:tpl_dev_test)).to eq(tpl_dev_test)
    end
  end

  describe "POST create", skip: "No POST route" do
    describe "with valid params" do
      it "creates a new TplDevTest" do
        expect {
          post :create, {:tpl_dev_test => valid_attributes}, valid_session
        }.to change(TplDevTest, :count).by(1)
      end

      it "assigns a newly created tpl_dev_test as @tpl_dev_test" do
        post :create, {:tpl_dev_test => valid_attributes}, valid_session
        expect(assigns(:tpl_dev_test)).to be_a(TplDevTest)
        expect(assigns(:tpl_dev_test)).to be_persisted
      end

      it "redirects to the created tpl_dev_test" do
        post :create, {:tpl_dev_test => valid_attributes}, valid_session
        expect(response).to redirect_to(TplDevTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tpl_dev_test as @tpl_dev_test" do
        post :create, {:tpl_dev_test => invalid_attributes}, valid_session
        expect(assigns(:tpl_dev_test)).to be_a_new(TplDevTest)
      end

      it "re-renders the 'new' template" do
        post :create, {:tpl_dev_test => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        FactoryGirl.build(:tpl_dev_test, argument: "AnotherString").attributes
      }

      it "updates the requested tpl_dev_test" do
        tpl_dev_test = TplDevTest.create! valid_attributes
        put :update, {:id => tpl_dev_test.to_param, :tpl_dev_test => new_attributes}, valid_session
        tpl_dev_test.reload
        expect(assigns(:tpl_dev_test).argument).not_to eq valid_attributes[:argument]
      end

      it "assigns the requested tpl_dev_test as @tpl_dev_test" do
        tpl_dev_test = TplDevTest.create! valid_attributes
        put :update, {:id => tpl_dev_test.to_param, :tpl_dev_test => valid_attributes}, valid_session
        expect(assigns(:tpl_dev_test)).to eq(tpl_dev_test)
      end

      it "redirects to the tpl_dev_test" do
        tpl_dev_test = TplDevTest.create! valid_attributes
        put :update, {:id => tpl_dev_test.to_param, :tpl_dev_test => valid_attributes}, valid_session
        expect(response).to redirect_to(tpl_dev_test)
      end
    end

    describe "with invalid params" do
      it "assigns the tpl_dev_test as @tpl_dev_test" do
        tpl_dev_test = TplDevTest.create! valid_attributes
        put :update, {:id => tpl_dev_test.to_param, :tpl_dev_test => invalid_attributes}, valid_session
        expect(assigns(:tpl_dev_test)).to eq(tpl_dev_test)
      end

      it "re-renders the 'edit' template" do
        tpl_dev_test = TplDevTest.create! valid_attributes
        put :update, {:id => tpl_dev_test.to_param, :tpl_dev_test => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy",  skip: "No DELETE route" do
    it "destroys the requested tpl_dev_test" do
      tpl_dev_test = TplDevTest.create! valid_attributes
      expect {
        delete :destroy, {:id => tpl_dev_test.to_param}, valid_session
      }.to change(TplDevTest, :count).by(-1)
    end

    it "redirects to the tpl_dev_tests list" do
      tpl_dev_test = TplDevTest.create! valid_attributes
      delete :destroy, {:id => tpl_dev_test.to_param}, valid_session
      expect(response).to redirect_to(tpl_dev_tests_url)
    end
  end

end
